### ISSUE TITLE
Template Binary sensor causing loop

### ISSUE THREAD

**Issue by barryodonovan** [OttoWinter/esphomelib#143] opened 2018-09-11 23:26 UTC
Template Binary Sensor is causing a loop during (mqtt?) setup on an ESP32 for me.

The code causing the issue is:
```
sensor:
  - platform: adc
    pin: GPIO32
    name: "Pellet Hopper Light"
    id: pellethopperlight
    update_interval: 60s
    attenuation: 6db

binary_sensor:
  - platform: template
    name: "Pellet Hopper Level"
    device_class: problem
    lambda: >-
      if (id(pellethopperlight).value > 0.2) {
        return true;
      } else {
        return false;
      }
```

After complilation and uploading the logs show multiple recurring MQTT setup debug output,  on my frontend sensors flick to/from unavailable states. No values appear to be polled and none are returned.

If I exclude the binary_sensor, the code runs correctly and the light levels are returned as expected.

**Comment by OttoWinter** [comment] 2018-09-20 09:13
Hmmm, I just compiled&run this code and it worked correctly. Anything more specific in the logs? What do you see if you enable verbose logs?

**Comment by OttoWinter** [comment] 2018-11-27 21:37
Closing this issue as I can't reproduce it...

**Closed by OttoWinter** 2018-11-27 21:37 UTC
