### ISSUE TITLE
[Feature request] Support for HX711

### ISSUE THREAD

**Issue by romanpeters** [OttoWinter/esphomelib#118] opened 2018-07-29 21:11 UTC
The HX711 is a small module that amplifies the signal coming from a load cell, used to measure weight.
I've got one laying around, but don't know how to use it with esphomelib.

**Comment by OttoWinter** [comment] 2018-07-31 17:48
Duplicate of https://github.com/OttoWinter/esphomeyaml/issues/76 - I will look into it

**Closed by OttoWinter** 2018-07-31 17:48 UTC
